title: å–œå¸ä¸Šæœˆçƒ(HCNtoMoon)
author: HCNtoMoon
baseurl: ""   
# The baseurl setting is only used if your blog or website is not going to sit at the root of your domain name. For example, if your Jekyll website will be at https://myawesomeblog.com/, leave the baseurl blank. If your blog or website will be at http://myawesomecompany.com/blog/, enter /blog as the baseurl.
url: https://hcntomoon.github.io/ # root address of the site
description: > # description of the site (multiple lines allowed)
  
  <p><b>ç«‹è¶³å–œå¸ï¼Œä¸“æ³¨é‡‘èï¼Œæ”¾çœ¼ä¸–ç•Œï¼Œå±•æœ›æœªæ¥ï¼<b></p>
  <p>ğŸš€<a href="https://hcntomoon.github.io/">å–œå¸ä¸Šæœˆçƒ(HCNtoMoon)ç½‘ç«™</a>æ˜¯ä¸€ä¸ªç”±èµ„æ·±å–œå¸çˆ±å¥½è€…åˆ›å»ºçš„éç›ˆåˆ©ç½‘ç«™ï¼Œè‡´åŠ›äºæ™®åŠå–œå¸çŸ¥è¯†ã€åˆ†äº«å–œå¸èµ„è®¯ï¼Œæˆä¸ºå€¼å¾—ä¿¡èµ–çš„ä¿¡æ¯åˆ†äº«å¹³å°ï¼ç›®å‰ç½‘ç«™å†…å®¹å·²è¡ç”Ÿåˆ°å¸åœˆã€é‡‘èã€æŠ€æœ¯ç­‰é¢†åŸŸã€‚</p>
  <p><i>å–œå¸ä¸Šæœˆçƒï¼Œç»é¡¶ååƒç§‹ï¼äººç”Ÿä½•æ‰€æ±‚ï¼Œå–œå¸ä¸Šæœˆçƒï¼</i></p> 
  <p>äº†è§£æ›´å¤šâ€”â€”ğŸŒ•<a href="/about">å…³äºæˆ‘</a>ã€‚</p> 

slogan: "å–œå¸ä¸Šæœˆçƒï¼Œç»é¡¶ååƒç§‹ï¼äººç”Ÿä½•æ‰€æ±‚ï¼Œå–œå¸ä¸Šæœˆçƒï¼"

keywords: "å–œå¸ä¸Šæœˆçƒ,HCNtoMoon,å–œå¸,å–œå¸å¤§äº‹è®°,å–œå¸å®˜ç½‘,å–œå¸ä»·æ ¼,å–œå¸äº¤æ˜“æ‰€,å–œå¸ä»·æ ¼èµ°åŠ¿,å–œå¸æ€ä¹ˆä¹°,å–œå¸æ˜¯ä»€ä¹ˆ,å–œå¸ç»´åŸºç™¾ç§‘,å–œå¸ hcn"


permalink: /:slug    # For example, the title â€œTips & Tricksâ€ can be slugified to â€œtips-tricksâ€ ,By slugifying a string, what is meant is adding a slug (-) in each of the string where there is a space.(æ°¸ä¹…é“¾æ¥æ ·å¼çš„é…ç½®æ–‡ä»¶)

favicon: "./logo.png" # relative path to site's favicon



#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# A Jekyll plugin to pull the page title from the first Markdown heading when none is specified.
  - jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true





theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "å›é¦–é¡µ.." # customize text for homepage link in post layout
  appearance_toggle: true # if appearance can be switched by user
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show website description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_article: true # show article posts added in _posts
  # show_old_projects: false # show old projects as cards, add in _data/home.yml
 
  show_reading_time: true # show number of words and reading time in the article posts
  # options for "home" page
  home:
    title_projects: é‡ç‚¹å†…å®¹
    title_article: æ–‡ç« 


highlighter: rouge

sass:
  style: :compressed



google_analytics:
  - G-E5VVCWR37F # New GA4 property      ,  UA is about to be deprecated on Jul 1, 2023,
  
  
  
  
  
  
# Exclude from processing.ä»å¤„ç†ä¸­æ’é™¤ã€‚
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/